# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_trans.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Trans(object):
    def setupUi(self, Trans):
        Trans.setObjectName("Trans")
        Trans.resize(800, 550)
        Trans.setMinimumSize(QtCore.QSize(800, 550))
        Trans.setMaximumSize(QtCore.QSize(800, 550))
        self.centralwidget = QtWidgets.QWidget(Trans)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 30, 541, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("苹方-简")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(34, 120, 151, 49))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setToolTipDuration(6)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(34, 190, 151, 49))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setObjectName("label_2")
        self.input = QtWidgets.QLabel(self.centralwidget)
        self.input.setGeometry(QtCore.QRect(360, 120, 401, 51))
        self.input.setText("")
        self.input.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.input.setWordWrap(True)
        self.input.setObjectName("input")
        self.output = QtWidgets.QLabel(self.centralwidget)
        self.output.setGeometry(QtCore.QRect(360, 180, 401, 51))
        self.output.setText("")
        self.output.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.output.setWordWrap(True)
        self.output.setObjectName("output")
        self.bt_input = QtWidgets.QPushButton(self.centralwidget)
        self.bt_input.setGeometry(QtCore.QRect(220, 130, 101, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_input.sizePolicy().hasHeightForWidth())
        self.bt_input.setSizePolicy(sizePolicy)
        self.bt_input.setMaximumSize(QtCore.QSize(167, 85))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bt_input.setFont(font)
        self.bt_input.setObjectName("bt_input")
        self.bt_output = QtWidgets.QPushButton(self.centralwidget)
        self.bt_output.setGeometry(QtCore.QRect(220, 200, 101, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_output.sizePolicy().hasHeightForWidth())
        self.bt_output.setSizePolicy(sizePolicy)
        self.bt_output.setMaximumSize(QtCore.QSize(167, 167))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bt_output.setFont(font)
        self.bt_output.setObjectName("bt_output")
        self.bt_trans = QtWidgets.QPushButton(self.centralwidget)
        self.bt_trans.setGeometry(QtCore.QRect(440, 260, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.bt_trans.setFont(font)
        self.bt_trans.setObjectName("bt_trans")
        self.info = QtWidgets.QLabel(self.centralwidget)
        self.info.setGeometry(QtCore.QRect(170, 340, 571, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info.setFont(font)
        self.info.setText("")
        self.info.setTextFormat(QtCore.Qt.PlainText)
        self.info.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.info.setWordWrap(True)
        self.info.setObjectName("info")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 420, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.encode = QtWidgets.QLineEdit(self.centralwidget)
        self.encode.setGeometry(QtCore.QRect(220, 270, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.encode.setFont(font)
        self.encode.setObjectName("encode")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setEnabled(True)
        self.label_5.setGeometry(QtCore.QRect(30, 260, 151, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAutoFillBackground(False)
        self.label_5.setObjectName("label_5")
        self.t_trans = QtWidgets.QTextEdit(self.centralwidget)
        self.t_trans.setGeometry(QtCore.QRect(180, 410, 561, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_trans.sizePolicy().hasHeightForWidth())
        self.t_trans.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.t_trans.setFont(font)
        self.t_trans.setObjectName("t_trans")
        Trans.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Trans)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        Trans.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Trans)
        self.statusbar.setEnabled(True)
        self.statusbar.setObjectName("statusbar")
        Trans.setStatusBar(self.statusbar)

        self.retranslateUi(Trans)
        self.bt_input.clicked.connect(self.input.update)
        self.bt_output.clicked.connect(self.output.update)
        self.bt_trans.clicked.connect(self.info.update)
        QtCore.QMetaObject.connectSlotsByName(Trans)

    def retranslateUi(self, Trans):
        _translate = QtCore.QCoreApplication.translate
        Trans.setWindowTitle(_translate("Trans", "拼音转汉字"))
        self.label.setText(_translate("Trans", "欢迎使用拼音转汉字程序，请按照操作步骤进行操作"))
        self.label_3.setText(_translate("Trans", "请选择输入文件"))
        self.label_2.setText(_translate("Trans", "请选择输出文件"))
        self.bt_input.setText(_translate("Trans", "选择文件"))
        self.bt_output.setText(_translate("Trans", "选择文件"))
        self.bt_trans.setText(_translate("Trans", "开始转换"))
        self.label_4.setText(_translate("Trans", "实时转换："))
        self.encode.setText(_translate("Trans", "utf-8"))
        self.label_5.setText(_translate("Trans", "请设置文件编码"))
